### ISSUE TITLE
Theme doesn't even work for BetterDiscord

### ISSUE THREAD

**Issue by Unanalyzed** [leeprky/Vintage#2]
I'm fairly experienced with BetterDiscord and I downloaded the theme for BD and enabled it and it doesn't even work. It doesn't show the enabled theme it doesn't even look like I have the theme enabled and it's just normal Discord.

**Comment by VanillaSpace** [comment]
You're probably using the 0.8.0 version instead of [0.9.4](https://github.com/leeprky/Vintage/blob/main/clients/betterdiscord/betterdiscord-vintage-094.theme.css)

**Comment by leeprky** [comment]
Fixed Release Issue
