### ISSUE TITLE
Skin change

### ISSUE THREAD

**Issue by Snwrk** [leeprky/vintage#3]
How do we change the skin?

**Comment by kaiyalith** [comment]
You need to access theme **SCSS file** in the themes folder, as I'm **Powercord** user it's located as follows:
`[Your Powercord installation path]\themes\vintage\clients\powercord\powercord-vintage-XXX.scss`
Then scroll down inside the file until you see `//Client skins` section. For other clients I dunno but I hope this might help you out.

**Comment by Snwrk** [comment]
Now what?

**Comment by Snwrk** [comment]
Nevermind figured it out.
